### ISSUE TITLE
Android Studio自编译闪退 android.content.pm.PackageManager$NameNotFoundException

### ISSUE THREAD

**Issue by diigu** [android-hacker/VirtualXposed#156]
android.content.pm.PackageManager$NameNotFoundException
启动后大约几秒时间内闪退,多台设备均存在闪退.
代码无修改.Android Studio 3.0.1,请问是什么问题?
错误日志:
```
--------- beginning of main
05-24 01:41:36.099 16765 16785 D LoaderTask: loadWorkspace: loading default favorites
05-24 01:41:36.107  1116  1129 W ActivityManager: Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://io.va.exposed:10171?v=7&cv=9 pkg=com.google.android.googlequicksearchbox } U=0: not found
05-24 01:41:36.802  1319  1319 V StatusBar: setLightsOn(true)
05-24 01:41:36.821  1319  1319 V StatusBar: setLightsOn(true)
05-24 01:41:36.824 16765 16765 W View    : requestLayout() improperly called by com.android.launcher3.graphics.GradientView{c87a5c3 V.ED..... ......I. 0,0-0,0 #7f0a00ac app:id/gradient_bg} during layout: running second layout pass
05-24 01:41:36.828  1319  1319 V StatusBar: setLightsOn(true)
05-24 01:41:36.843  1319  1319 V StatusBar: setLightsOn(true)
05-24 01:41:36.852 16765 16765 I Choreographer: Skipped 41 frames!  The application may be doing too much work on its main thread.
05-24 01:41:36.859  1319  1319 V StatusBar: setLightsOn(true)
05-24 01:41:36.877  1319  1319 I chatty  : uid=10002(com.android.systemui) identical 1 line
05-24 01:41:36.881  1319  1319 V StatusBar: setLightsOn(true)
05-24 01:41:36.882  1116  1140 I ActivityManager: Displayed io.va.exposed/io.virtualapp.home.NewHomeActivity: +1s887ms
05-24 01:41:36.890  1319  1319 V StatusBar: setLightsOn(true)
05-24 01:41:36.909  1319  1319 I chatty  : uid=10002(com.android.systemui) identical 4 lines
05-24 01:41:36.918  1319  1319 V StatusBar: setLightsOn(true)
05-24 01:41:36.941   739   739 D QCOM PowerHAL: LAUNCH HINT: OFF
05-24 01:41:36.951 16765 16785 W System.err: android.content.pm.PackageManager$NameNotFoundException: de.robv.android.xposed.installer
05-24 01:41:36.951 16765 16785 W System.err: 	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:378)
05-24 01:41:36.951 16765 16785 W System.err: 	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:360)
05-24 01:41:36.951 16765 16785 W System.err: 	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1394)
05-24 01:41:36.951 16765 16785 W System.err: 	at com.google.android.apps.nexuslauncher.CustomIconProvider.getRoundIcon(CustomIconProvider.java:127)
05-24 01:41:36.951 16765 16785 W System.err: 	at com.google.android.apps.nexuslauncher.CustomIconProvider.getIcon(CustomIconProvider.java:117)
05-24 01:41:36.951 16765 16785 W System.err: 	at com.android.launcher3.IconCache.getFullResIcon(IconCache.java:182)
05-24 01:41:36.951 16765 16785 W System.err: 	at com.android.launcher3.IconCache.getFullResIcon(IconCache.java:178)
05-24 01:41:36.951 16765 16785 W System.err: 	at com.android.launcher3.IconCache.cacheLocked(IconCache.java:537)
05-24 01:41:36.951 16765 16785 W System.err: 	at com.android.launcher3.IconCache.getTitleAndIcon(IconCache.java:479)
05-24 01:41:36.951 16765 16785 W System.err: 	at com.android.launcher3.IconCache.getTitleAndIcon(IconCache.java:451)
05-24 01:41:36.951 16765 16785 W System.err: 	at com.android.launcher3.AllAppsList.add(AllAppsList.java:81)
05-24 01:41:36.952 16765 16785 W System.err: 	at com.android.launcher3.model.LoaderTask.loadAllApps(LoaderTask.java:821)
05-24 01:41:36.952 16765 16785 W System.err: 	at com.android.launcher3.model.LoaderTask.run(LoaderTask.java:164)
05-24 01:41:36.952 16765 16785 W System.err: 	at android.os.Handler.handleCallback(Handler.java:790)
05-24 01:41:36.952 16765 16785 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-24 01:41:36.952 16765 16785 W System.err: 	at android.os.Looper.loop(Looper.java:164)
05-24 01:41:36.952 16765 16785 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:65)
05-24 01:41:37.127  1319  1319 V StatusBar: setLightsOn(true)
05-24 01:41:37.134  2045 16453 V rsC++   : RS Message thread exiting.
05-24 01:41:37.150 16765 16785 D ProtoStore: no cached data
05-24 01:41:37.150 16765 16785 D ProtoStore: no cached data
05-24 01:41:37.160  1319  1319 V StatusBar: setLightsOn(true)
05-24 01:41:37.315  1319  1319 I chatty  : uid=10002(com.android.systemui) identical 4 lines
05-24 01:41:37.316  1319  1319 V StatusBar: setLightsOn(true)
05-24 01:41:37.867   724  1105 D audio_hw_primary: disable_audio_route: usecase(1) reset and update mixer path: low-latency-playback speaker
05-24 01:41:37.871   724  1105 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
05-24 01:41:38.771 16765 16844 I zygote  : System.exit called, status: 10
05-24 01:41:38.771 16765 16844 I AndroidRuntime: VM exiting with result code 10, cleanup skipped.
05-24 01:41:38.809  1116  1242 W InputDispatcher: channel '436fa50 io.va.exposed/io.virtualapp.home.NewHomeActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
05-24 01:41:38.809  1116  1242 E InputDispatcher: channel '436fa50 io.va.exposed/io.virtualapp.home.NewHomeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
05-24 01:41:36.112  1116  1129 W ActivityManager: Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://io.va.exposed:10171?v=7&cv=9 pkg=com.google.android.googlequicksearchbox } U=0: not found
05-24 01:41:38.833  1116  1453 I WindowManager: WIN DEATH: Window{436fa50 u0 io.va.exposed/io.virtualapp.home.NewHomeActivity}
05-24 01:41:38.833  1116  1453 W InputDispatcher: Attempted to unregister already unregistered input channel '436fa50 io.va.exposed/io.virtualapp.home.NewHomeActivity (server)'
05-24 01:41:38.836   697   697 I Zygote  : Process 16765 exited cleanly (10)
05-24 01:41:38.837  1116  1130 I ActivityManager: Process io.va.exposed (pid 16765) has died: fore TOP 
05-24 01:41:38.837  1116  1135 W zygote64: kill(-16765, 9) failed: No such process
05-24 01:41:38.837  1116  1135 I zygote64: Successfully killed process cgroup uid 10171 pid 16765 in 0ms
05-24 01:41:38.838  1116  1130 W ActivityManager: Force removing ActivityRecord{cd6a023 u0 io.va.exposed/io.virtualapp.home.NewHomeActivity t166}: app died, no saved state
05-24 01:41:38.847  1319  1319 V StatusBar: setLightsOn(true)
05-24 01:41:38.858   606   631 E SurfaceFlinger: Failed to find layer (io.va.exposed/io.virtualapp.home.NewHomeActivity#0) in layer parent (no-parent).
05-24 01:41:38.886  1116  1140 W ActivityManager: setHasOverlayUi called on unknown pid: 16765
05-24 01:41:38.913  2045  2196 I Adreno  : QUALCOMM build                   : 594927b, I916dfac403
05-24 01:41:38.913  2045  2196 I Adreno  : Build Date                       : 10/11/17
05-24 01:41:38.913  2045  2196 I Adreno  : OpenGL ES Shader Compiler Version: EV031.21.02.00
05-24 01:41:38.913  2045  2196 I Adreno  : Local Branch                     : mybranch28618966
05-24 01:41:38.913  2045  2196 I Adreno  : Remote Branch                    : quic/gfx-adreno.lnx.6.4.9-rel
05-24 01:41:38.913  2045  2196 I Adreno  : Remote Branch                    : NONE
05-24 01:41:38.913  2045  2196 I Adreno  : Reconstruct Branch               : NOTHING
05-24 01:41:38.919  2045  2196 I Adreno  : PFP: 0x005ff087, ME: 0x005ff063
05-24 01:41:38.923  2045  2196 I zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 1
05-24 01:41:38.925  2045  2196 I OpenGLRenderer: Initialized EGL, version 1.4
05-24 01:41:38.925  2045  2196 D OpenGLRenderer: Swap behavior 2
05-24 01:41:39.462  2045  2196 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
```

**Comment by tiann** [comment]
关闭 Instant Run

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/blob/exposed/VirtualApp/app/src/main/java/io/virtualapp/VCommends.java#L65 注释掉
