### ISSUE TITLE
Force close on try install any app in v 0.10.0 on x86 emulator

### ISSUE THREAD

**Issue by Enyby** [android-hacker/VirtualXposed#174]
**Describe the bug**
On add any app force close VirtualXposed due Exception 
```
FATAL EXCEPTION: main
Process: io.va.exposed, PID: 2109
android.content.res.Resources$NotFoundException: String resource ID #0x7f120050
       at android.content.res.Resources.getText(Resources.java:331)
       at android.content.res.Resources.getString(Resources.java:377)
       at android.content.res.Resources.getString(Resources.java:401)
       at io.virtualapp.sys.InstallerActivity$1.lambda$update$77$InstallerActivity$1(InstallerActivity.java:133)
       at io.virtualapp.sys.InstallerActivity$1$$Lambda$0.run(Unknown Source)
       at android.app.Activity.runOnUiThread(Activity.java:5849)
       at io.virtualapp.sys.InstallerActivity$1.update(InstallerActivity.java:119)
       at io.virtualapp.sys.Installd.lambda$handleOptApp$73$Installd(Installd.java:170)
       at io.virtualapp.sys.Installd$$Lambda$5.onDone(Unknown Source)
       at org.jdeferred.android.AndroidDeferredObject$InternalHandler.handleMessage(AndroidDeferredObject.java:82)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```
ID of string resource always same.

**To Reproduce**
Install any app.

**Expected behavior**
Installed app.

**Screenshots**
[ 1805_half_mute.zip](https://github.com/android-hacker/VirtualXposed/files/2054586/1805_half_mute.zip)

**Desktop (please complete the following information):**
Not applicable.

**Smartphone (please complete the following information):**
Android 7.0.0 and Android 7.1.0 is same.
Used Genymotion emulator.

**Additional context**
Logcat from crash:
[logcat.txt](https://github.com/android-hacker/VirtualXposed/files/2054598/logcat.txt)

**Comment by Enyby** [comment]
I tried removing the x86 library and installing it in Nox 5.1. Version 0.9.9 worked there. v0.10.0 falls, even with ARM libraries only. The error is the same.

**Comment by Enyby** [comment]
Found source of bug. Mistake on type:
https://github.com/android-hacker/VirtualXposed/blob/11b556151c7fe4c2e66d7ee974fa8188f4aba2b3/VirtualApp/app/src/main/res/values/strings.xml#L77
https://github.com/android-hacker/VirtualXposed/blob/11b556151c7fe4c2e66d7ee974fa8188f4aba2b3/VirtualApp/app/src/main/res/values-zh-rCN/strings.xml#L73
https://github.com/android-hacker/VirtualXposed/blob/11b556151c7fe4c2e66d7ee974fa8188f4aba2b3/VirtualApp/app/src/main/res/values-es/strings.xml#L77
https://github.com/android-hacker/VirtualXposed/blob/11b556151c7fe4c2e66d7ee974fa8188f4aba2b3/VirtualApp/app/src/main/java/io/virtualapp/sys/InstallerActivity.java#L133
https://github.com/android-hacker/VirtualXposed/blob/11b556151c7fe4c2e66d7ee974fa8188f4aba2b3/VirtualApp/app/src/main/java/io/virtualapp/sys/InstallerActivity.java#L311

**Comment by Enyby** [comment]
Pull request:
https://github.com/android-hacker/VirtualXposed/pull/175

**Comment by Enyby** [comment]
Currently v0.10.0 only usable if in system used next locales: es or zh-CN.
On other locales v0.10.0 will crash.

**Comment by tiann** [comment]
@Enyby Thank you.

I release a new version [0.10.1](https://github.com/android-hacker/VirtualXposed/releases/tag/0.10.1) and test it myself, seems working well :)
