### ISSUE TITLE
Crash when focusing on EditText with Autofill enabled

### ISSUE THREAD

**Issue by Librazy** [android-hacker/VirtualXposed#200]
**Describe the bug**
App installed in vxp crashes when focusing input box with Autofill enabled.

**To Reproduce**
1. Enable any Autofill service like Google. etc
2. Open xposed installer or other app with input. Verify everything works without input box.
3. Try focus on EditText like search bar of xposed installer. It crashes.
4. Disable Autofill service
5. Try again and everything works including input.

**Expected behavior**
Everything works including Autofill.

**Screenshots**
TBD

**Smartphone (please complete the following information):**
 - Device: Oneplus 6
 - OS: OOS 5.1.5 (Oreo 8.1, SDK 27)
 - Browser N/A
 - Version 0.10.1 w/ xposed 91

**Additional context**
Logcat: (Test with Google Autofill with Instagram)
https://0bin.net/paste/UvK3uKuc6xCD5b9h#IrjRnen9+PvZc76S9B+dUkmrgHxES9cuaslvcr8bnMc

**Comment by tiann** [comment]
Hi, i have received the feedback, but i try it in my Android 8.0 device, it works well.

I need to find a Android 8.1 device to test, it may take a while.

**Comment by Librazy** [comment]
Feel free to ask me for more details/logcats, thank you!

**Comment by tiann** [comment]
sorry, i find a OnePlus 8.1 on http://mtc.baidu.com/tinypace/main#/

I rent it but can not reproduce the bug.

**Comment by tiann** [comment]
you caner refer VirtualXposed's source code: com.lody.virtual.client.hook.proxies.view.AutoFillManagerStub

and fix it yourself.

**Comment by tiann** [comment]
I try Fiilr to autofill, it works well. maybe it is the AutoFillService you choosed can not work in VXP.

**Comment by Librazy** [comment]
FYI I tried with Keepass2Android and Google, both fails with similar stacktrace.

**Comment by tiann** [comment]
the APP i rent is ￥0.6/min，i have waste ￥27. can you fix It yourself？

**Comment by Librazy** [comment]
I'll look into this, thanks.

**Comment by koko115** [comment]
I have this problem too 0.12.1 S9+ exynos

**Comment by houfukude** [comment]
同样问题

- Device: Pixel 2 XL
- OS: Stock Android  (Oreo 8.1.0, SDK 27)
- Browser N/A
- Version 0.12.1 w/ xposed 91

简单的抓了一下log 希望有所帮助
 **复现方式:**
打开自带xposed Installer
切换到Download页面
点击右上角搜索.

```
    --------- beginning of crash
07-02 15:33:24.475 25968-25968/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.robv.android.xposed.installer, PID: 25968
    java.lang.IllegalArgumentException: ComponentInfo{de.robv.android.xposed.installer/de.robv.android.xposed.installer.WelcomeActivity} is not a valid package
        at android.os.Parcel.readException(Parcel.java:2009)
        at android.os.Parcel.readException(Parcel.java:1951)
        at android.view.autofill.IAutoFillManager$Stub$Proxy.startSession(IAutoFillManager.java:397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.lody.virtual.client.hook.base.MethodProxy.call(MethodProxy.java:92)
        at com.lody.virtual.client.hook.base.MethodInvocationStub$HookInvocationHandler.invoke(MethodInvocationStub.java:186)
        at java.lang.reflect.Proxy.invoke(Proxy.java:913)
        at $Proxy46.startSession(Unknown Source)
        at android.view.autofill.AutofillManager.startSessionLocked(AutofillManager.java:1012)
        at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:604)
        at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:575)
        at android.view.View.notifyEnterOrExitForAutoFillIfNeeded(View.java:6980)
        at android.view.View.layout(View.java:19687)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1780)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1546)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1780)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1546)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1780)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1546)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.support.v7.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1642)
        at android.support.v7.widget.LinearLayoutCompat.layoutHorizontal(LinearLayoutCompat.java:1631)
        at android.support.v7.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1406)
        at android.support.v7.widget.SearchView.onLayout(SearchView.java:830)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.support.v7.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1642)
        at android.support.v7.widget.LinearLayoutCompat.layoutHorizontal(LinearLayoutCompat.java:1631)
        at android.support.v7.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1406)
        at android.support.v7.widget.ActionMenuView.onLayout(ActionMenuView.java:439)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.support.v7.widget.Toolbar.layoutChildRight(Toolbar.java:1961)
        at android.support.v7.widget.Toolbar.onLayout(Toolbar.java:1746)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
07-02 15:33:24.478 777-2596/? D/audio_hw_primary: out_write: retry previous failed cal level set
07-02 15:33:24.478 25968-25968/? I/XApp: uncaught :Thread[main,5,main]
    java.lang.IllegalArgumentException: ComponentInfo{de.robv.android.xposed.installer/de.robv.android.xposed.installer.WelcomeActivity} is not a valid package
        at android.os.Parcel.readException(Parcel.java:2009)
        at android.os.Parcel.readException(Parcel.java:1951)
        at android.view.autofill.IAutoFillManager$Stub$Proxy.startSession(IAutoFillManager.java:397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.lody.virtual.client.hook.base.MethodProxy.call(MethodProxy.java:92)
        at com.lody.virtual.client.hook.base.MethodInvocationStub$HookInvocationHandler.invoke(MethodInvocationStub.java:186)
        at java.lang.reflect.Proxy.invoke(Proxy.java:913)
        at $Proxy46.startSession(Unknown Source)
        at android.view.autofill.AutofillManager.startSessionLocked(AutofillManager.java:1012)
        at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:604)
        at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:575)
        at android.view.View.notifyEnterOrExitForAutoFillIfNeeded(View.java:6980)
        at android.view.View.layout(View.java:19687)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1780)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1546)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1780)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1546)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1780)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1546)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.support.v7.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1642)
        at android.support.v7.widget.LinearLayoutCompat.layoutHorizontal(LinearLayoutCompat.java:1631)
        at android.support.v7.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1406)
        at android.support.v7.widget.SearchView.onLayout(SearchView.java:830)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.support.v7.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1642)
        at android.support.v7.widget.LinearLayoutCompat.layoutHorizontal(LinearLayoutCompat.java:1631)
        at android.support.v7.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1406)
        at android.support.v7.widget.ActionMenuView.onLayout(ActionMenuView.java:439)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.support.v7.widget.Toolbar.layoutChildRight(Toolbar.java:1961)
        at android.support.v7.widget.Toolbar.onLayout(Toolbar.java:1746)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
07-02 15:33:24.479 25968-25968/? I/XApp:     at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
07-02 15:33:24.533 25968-25968/? I/zygote: System.exit called, status: 0
07-02 15:33:24.533 25968-25968/? I/AndroidRuntime: VM exiting with result code 0, cleanup skipped.
07-02 15:33:24.581 1142-1592/? W/InputDispatcher: channel '5fbb2b0 de.robv.android.xposed.installer/de.robv.android.xposed.installer.WelcomeActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-02 15:33:24.581 1142-1592/? E/InputDispatcher: channel '5fbb2b0 de.robv.android.xposed.installer/de.robv.android.xposed.installer.WelcomeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
    
    --------- beginning of system
```

**Comment by tiann** [comment]
@houfukude 谢谢。

已修复：https://github.com/android-hacker/VirtualXposed/commit/cf308921a0e1131d9ea6ad39ccfb50eecab39b79

**Comment by nhayfield** [comment]
I am having this same issue in React Native
