### ISSUE TITLE
红米Note4X上无法运行

### ISSUE THREAD

**Issue by IPL** [android-hacker/VirtualXposed#53]
红米Note4X, 已root, 安装了Xposed Installer. 在安装Virtual Xposed 0.8.8之后, 运行出下面的错误. 请帮忙看一下, 多谢.

```
04-03 12:17:10.111 6012-6012/io.va.exposed:x E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: io.va.exposed:x, PID: 6012
                                                               java.lang.RuntimeException: Unable to get provider com.lody.virtual.server.BinderProvider: java.lang.RuntimeException: Package manager has died
                                                                   at android.app.ActivityThread.installProvider(ActivityThread.java:5499)
                                                                   at android.app.ActivityThread.installContentProviders(ActivityThread.java:5025)
                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4965)
                                                                   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
                                                                   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
                                                                   at android.app.ActivityThread.handleBindApplication(<Xposed>)
                                                                   at android.app.ActivityThread.access$1700(ActivityThread.java:180)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                   at android.os.Looper.loop(Looper.java:207)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5811)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)
                                                                   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
                                                                Caused by: java.lang.RuntimeException: Package manager has died
                                                                   at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:139)
                                                                   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
                                                                   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
                                                                   at android.app.ApplicationPackageManager.getPackageInfo(<Xposed>)
                                                                   at com.lody.virtual.server.am.VActivityManagerService.onCreate(VActivityManagerService.java:115)
                                                                   at com.lody.virtual.server.am.VActivityManagerService.systemReady(VActivityManagerService.java:97)
                                                                   at com.lody.virtual.server.BinderProvider.onCreate(BinderProvider.java:46)
                                                                   at android.content.ContentProvider.attachInfo(ContentProvider.java:1811)
                                                                   at android.content.ContentProvider.attachInfo(ContentProvider.java:1786)
                                                                   at android.app.ActivityThread.installProvider(ActivityThread.java:5496)
                                                                   at android.app.ActivityThread.installContentProviders(ActivityThread.java:5025) 
                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4965) 
                                                                   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
                                                                   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) 
                                                                   at android.app.ActivityThread.handleBindApplication(<Xposed>) 
                                                                   at android.app.ActivityThread.access$1700(ActivityThread.java:180) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                   at android.os.Looper.loop(Looper.java:207) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5811) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768) 
                                                                   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 
                                                                Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
                                                                   at android.os.BinderProxy.transactNative(Native Method)
                                                                   at android.os.BinderProxy.transact(Binder.java:513)
                                                                   at android.content.pm.IPackageManager$Stub$Proxy.getPackageInfo(IPackageManager.java:2181)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.lody.virtual.client.hook.proxies.pm.MethodProxies$GetPackageInfo.call(MethodProxies.java:641)
                                                                   at com.lody.virtual.client.hook.base.MethodInvocationStub$HookInvocationHandler.invoke(MethodInvocationStub.java:186)
                                                                   at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                                   at $Proxy3.getPackageInfo(Unknown Source)
                                                                   at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:134)
                                                                   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
                                                                   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) 
                                                                   at android.app.ApplicationPackageManager.getPackageInfo(<Xposed>) 
                                                                   at com.lody.virtual.server.am.VActivityManagerService.onCreate(VActivityManagerService.java:115) 
                                                                   at com.lody.virtual.server.am.VActivityManagerService.systemReady(VActivityManagerService.java:97) 
                                                                   at com.lody.virtual.server.BinderProvider.onCreate(BinderProvider.java:46) 
                                                                   at android.content.ContentProvider.attachInfo(ContentProvider.java:1811) 
                                                                   at android.content.ContentProvider.attachInfo(ContentProvider.java:1786) 
                                                                   at android.app.ActivityThread.installProvider(ActivityThread.java:5496) 
                                                                   at android.app.ActivityThread.installContentProviders(ActivityThread.java:5025) 
                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4965) 
                                                                   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) 
                                                                   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) 
                                                                   at android.app.ActivityThread.handleBindApplication(<Xposed>) 
                                                                   at android.app.ActivityThread.access$1700(ActivityThread.java:180) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                   at android.os.Looper.loop(Looper.java:207) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5811) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768) 
                                                                   at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 

```

**Comment by tiann** [comment]
你本机Xposed启用了什么插件？

**Comment by IPL** [comment]
安装了com.bigsing.changer 这个插件. 1.22版没问题, 自升级到1.23之后, VirtualXposed会有问题.

**Comment by tiann** [comment]
SDK版本，API version等信息不要改。本机安装过，不要在VirtualXposed里面装。
