### ISSUE TITLE
一旦启用了xposed插件，wcdb抛出异常，微信就卡在地球页面了

### ISSUE THREAD

**Issue by captain-black** [android-hacker/VirtualXposed#74]
一旦启用了xposed插件，wcdb就跑出异常，微信卡在启动时地球页面了。

微信版本6.6.1
VXP版本0.9.7
日志如下：

04-18 22:23:00.843 29925-29973/? E/AndroidRuntime: FATAL EXCEPTION: parallels-5
                                                   Process: com.tencent.mm, PID: 29925
                                                   com.tencent.wcdb.database.SQLiteException: no such table: userinfo (code 1, errno 0): 
                                                       at com.tencent.wcdb.database.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
                                                       at com.tencent.wcdb.database.SQLiteConnection.executeForCursorWindow(SourceFile:910)
                                                       at com.tencent.wcdb.database.SQLiteSession.executeForCursorWindow(SourceFile:789)
                                                       at com.tencent.wcdb.database.SQLiteQuery.fillWindow(SourceFile:63)
                                                       at com.tencent.wcdb.database.SQLiteCursor.fillWindow(SourceFile:146)
                                                       at com.tencent.wcdb.database.SQLiteCursor.getCount(SourceFile:135)
                                                       at com.tencent.wcdb.AbstractCursor.moveToPosition(SourceFile:200)
                                                       at com.tencent.wcdb.AbstractCursor.moveToFirst(SourceFile:240)
                                                       at com.tencent.wcdb.CursorWrapper.moveToFirst(SourceFile:69)
                                                       at com.tencent.mm.storage.t.get(SourceFile:112)
                                                       at com.tencent.mm.storage.bc.cdg(SourceFile:34)
                                                       at com.tencent.mm.kernel.a.bh(SourceFile:229)
                                                       at com.tencent.mm.kernel.a.initialize(SourceFile:555)
                                                       at com.tencent.mm.plugin.h.a.execute(SourceFile:25)
                                                       at com.tencent.mm.kernel.a.c.a(SourceFile:57)
                                                       at com.tencent.mm.kernel.a.c$3.call(SourceFile:206)
                                                       at com.tencent.mm.kernel.a.b.e$1.run(SourceFile:264)
                                                       at android.os.Handler.handleCallback(Handler.java:754)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:163)
                                                       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by captain-black** [comment]
补充，手机是红米5A
Android系统 7.1.2
MIUI 9.5.3.0 稳定版

**Comment by tiann** [comment]
什么插件？

**Comment by captain-black** [comment]
自己的插件，禁用了某段操作微信打开WCDB的代码就可以了。裸xposed的时候代码没问题的，在vxp里就出问题，我先做了绕开处理了

**Comment by tiann** [comment]
@captain-black 能分享一下吗，是否跟提前加载了wcdb相关的类有关？

**Comment by captain-black** [comment]
在微信打开EnMicroMsg.db时，我hook来打印出数据库密码，没影响到微信的逻辑！

    
        
            
                
                    
                        
                    
                    
                        
                            captainblack.soul
                            
                            
                                
                                    邮箱：captainblack.soul@gmail.com
                                
                        
                    
                
            
        
    
签名由 网易邮箱大师 定制
在2018年04月19日 20:44，weishu 写道： @captain-black 能分享一下吗，是否跟提前加载了wcdb相关的类有关？

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/android-hacker/VirtualXposed","title":"android-hacker/VirtualXposed","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/android-hacker/VirtualXposed"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tiann in #74: @captain-black 能分享一下吗，是否跟提前加载了wcdb相关的类有关？"}],"action":{"name":"View Issue","url":"https://github.com/android-hacker/VirtualXposed/issues/74#issuecomment-382719961"}}}

**Comment by tiann** [comment]
也就是说，你之前直接hook了微信对数据库的打开操作，这样会有问题吗？

之前有人反馈 hook native/static 方法有bug，是否跟这个有关？

**Comment by captain-black** [comment]
就是以上代码引起了问题，注释了就正常了
